# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='opportunity_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_title', models.CharField(max_length=20)),
                ('opportunity_story', models.TextField()),
                ('opportunity_date', models.DateTimeField()),
            ],
        ),
    ]
