# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity_post',
            name='opportunity_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
