# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_opportunity_post_opportunity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='career_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_title', models.CharField(max_length=20)),
                ('career_description', models.TextField()),
                ('career_payment', models.FloatField()),
                ('career_starting_time', models.DateTimeField()),
                ('career_finish_time', models.DateTimeField()),
            ],
        ),
    ]
