# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_career_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity_post',
            name='opportunity_title',
            field=models.CharField(max_length=70),
        ),
    ]
