# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_onclickcart_cart_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='onclickcart',
            name='cart_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
