# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_specific_products_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='specific_products',
            name='product_price',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
