# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_specific_products_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='specific_products',
            name='product_promo',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
