# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_specific_products_product_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specific_products',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
    ]
