# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20160328_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='specific_products',
            name='product_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
